### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by indiesquidge**
Hey @FoxHax,

Love this Firewatch clock you made here. I took a look around the project and decided to do just a bit of refactoring. I'd love to know how you feel about the changes I've made!
#### JavaScript

Refactored `clock.js` to be more readable, maintainable, and declarative by separating it's functionality into named functions. Biggest thing here was making the `updateClock` function more concise and easier to understand.

One thing I intentionally removed was the `setTimeout` that was run every millisecond for the whole `updateClock` function. While this does exterminate the benefit of having the clock remain up to date to the second on the browser (well, millisecond even), it alleviates the need to repaint the background image, find the DOM elements, update the DOM elements, etc., which was happening _tens of thousands of times per second_. Now, perhaps we could discuss the best possible way for only the actual updates to run in a `setTimeout` (i.e, updating `wordClockElem`, `digitalClockElem`, and the `document.title`), but I personally think it's fine without the `setTimeout`.
#### HTML

The updates made to this file are mostly just indentation. I updated the © to be more semantic and accessible by wrapping it in a `<span>`. The really change was using an SVG as the banner ribbon instead of a static image. Not only does this look sharper on the screen, but it saves us a full HTTP request since we no longer have an image to fetch. I also updated the favicon to be more retina display friendly.
#### CSS

Only real change here was the necessary updates to the `.ribbon` class, which is now an SVG element.

---
### For the Future
- The main thing I'd still like to do is make this mobile-friendly.
- I am also working on porting it over to a be a Chrome Plugin Extension for new tabs.
- Having a different background image for `Day.jpg` would be nice, considering it's the same image as `Sunset.jpg`, only with a slightly different shade

That's all for now! Thanks again for making this awesome little clock, man :)

Huge fan of the game 💛 
# Hacktoberfest

– Austin

### CODE REVIEW

**Comment by FoxHax** [comment]
I think I just accidentally wrote my comment into the merge commit thing... forgive me, I'm pretty new with github!
But yes! I love the sound of it. It was always too slow to load and the banner looked a lil weird as bitmap. I started the clock to try to fix my js skills but didn't get too far.
Also the new tab page sounds cool, I use momentum right now for that.
Cool to see someone else who loves the game!

**Comment by FoxHax** [comment]
Also it appears the clock doesn't actually update at all without the setTimeout....

**Comment by indiesquidge** [comment]
Haha, no worries! Welcome to GitHub!

**Comment by indiesquidge** [comment]
Yeah, without the `setInterval` (it was `setInterval` this whole time, not `setTimeout`, my apologies) the clock would only update on a refresh of the browser. This is the big pitfall to not using `setInterval`. What I am thinking would be okay is to have the time display immediately on page load, and then update the clock on like a 5-15 second interval or something.

**Comment by FoxHax** [comment]
Can't `setInterval` be used to update every 15 seconds? Or does that make the page not load for 15 seconds or something?

Also I was thinking with the backgrounds, it would be cool to make them have a parallax effect (similar to the [Halo Reach menu](http://halome.nu/reach)), perhaps using the layers from [here](http://www.firewatchgame.com/). Then again there is only one set of wallpaper layers available... so maybe we could get in contact with Campo Santo? We can only hope

**Comment by FoxHax** [comment]
And one more thing I was going to add was a loading screen while all the elements loaded, and also for the other backgrounds to be prefetched so when they transition, there's no lag in loading the next wallpaper

**Comment by indiesquidge** [comment]
Well, `setInterval` can be used update the time, but if `setInterval` was wrapped around the entire process and only went off every 15 seconds, then yeah, basically nothing (other than the SVG ribbon) would load at all for the first 15 seconds.

I submitted another [PR](https://github.com/FoxHax/FoxHax.github.io/pull/2) to fix a dumb issue I created where the clock would display `undefined`, and also to update the clock every five seconds with `setInterval`.

**Comment by indiesquidge** [comment]
The parallax idea does sound quite cool! I've never done it before, so I don't know how difficult it is, but it would be fun. The difficulty certainly is around getting all layers for all the times of day. Where did you originally get all of the different colored static backgrounds?

**Comment by indiesquidge** [comment]
I'm not sure I understand what you mean by a loading screen while all the elements loaded. Is there a lag time for you on initial load? There are really only four files (`index.html`, `settings.css`, `clock.js`, and whatever background image is needed at the time) that I can think of that need to be loaded right off the bat, so I'm not sure there is a necessity for a loading screen.

Perhaps this is just because I'm running the code locally, but a background image switch feels pretty seamless to me. Does it look more jarring when running in production?

**Comment by FoxHax** [comment]
The original backgrounds were all from their website (on a downloads page) and the night one was made by someone on the sub. The background is what takes time to load for me, line by line.

**Comment by FoxHax** [comment]
You can check on http://foxhax.github.io too

**Pull request merged**
